language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-yui3-app' ]; then cd .. && eval "mv $currentfolder generator-yui3-app" && cd generator-yui3-app; fi

